#!/bin/bash
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_0_5 --joint_noise_error 0 --transl_noise_error 5 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_10_5 --joint_noise_error 10 --transl_noise_error 5 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_30_5 --joint_noise_error 30 --transl_noise_error 5 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_100_5 --joint_noise_error 100 --transl_noise_error 5 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_10_0 --joint_noise_error 10 --transl_noise_error 0 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_30_0 --joint_noise_error 30 --transl_noise_error 0 --parallel_generation True
python generate_data.py --directories_file configs/machine_directories/bohg-ws-3_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_vb_100_0 --joint_noise_error 100 --transl_noise_error 0 --parallel_generation True




#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_10_0 --joint_noise_error 10 --transl_noise_error 0
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_30_0 --joint_noise_error 30 --transl_noise_error 0
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_100_0 --joint_noise_error 100 --transl_noise_error 0
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_0_5 --joint_noise_error 0 --transl_noise_error 5
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_10_5 --joint_noise_error 10 --transl_noise_error 5
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_30_5 --joint_noise_error 30 --transl_noise_error 5
#python generate_data.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/data_generation/data_generation.yml --experiment_name obj_v_100_5 --joint_noise_error 100 --transl_noise_error 5
#python run.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/experiments/experiment_config_obj.yml --experiment_name obj_v_10_0 --test_ranges [12] --times_ahead [12] --single_times True --joint_noise_level 10 --transl_noise_level 0 --data_type vertices
#python run.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/experiments/experiment_config_obj.yml --experiment_name obj_v_30_0 --test_ranges [12] --times_ahead [12] --single_times True --joint_noise_level 30 --transl_noise_level 0 --data_type vertices
#python run.py --directories_file configs/machine_directories/juno_directories.yml --config_file configs/experiments/experiment_config_obj.yml --experiment_name obj_v_100_5 --test_ranges [12] --times_ahead [12] --single_times True --joint_noise_level 100 --transl_noise_level 5 --data_type vertices