exp_dir_base: /scr/msalvato/predictive_hands #doesn't have data

mano_smplx_file: /scr/msalvato/grab_data/grab/MANO_SMPLX_vertex_ids.pkl
grab_path: /scr/msalvato/grab_data/grab/grab_dataset/grab
model_path: /scr/msalvato/grab_data/grab/models_smplx_v1_1/models
data_path: /scr/msalvato/grab_data/grab/predictive_data_points
image_temp_path: /scr/msalvato/grab_data/grab/predictive_data_points/image_temp