exp_dir_base: /home/bee/predictive_hands/predictive_hands_experiments

mano_smplx_file: /home/bee/predictive_hands/grab_data/grab/MANO_SMPLX_vertex_ids.pkl
grab_path: /home/bee/predictive_hands/grab_data/grab/grab_dataset/grab
model_path: /home/bee/predictive_hands/grab_data/grab/models_smplx_v1_1/models
data_path: /home/bee/predictive_hands/grab_data/grab/predictive_data
